// ============================================
// Core Types for Babblet v2
// Real-time Teacher Questioning AI
// ============================================

// Semantic event types detected by Gemini
export type SemanticEventType = 
  | 'claim'
  | 'topic_shift'
  | 'definition'
  | 'example'
  | 'argument'
  | 'evidence'
  | 'conclusion'
  | 'question'
  | 'unclear';

export interface SemanticEvent {
  id: string;
  type: SemanticEventType;
  content: string;
  confidence: number;
  timestamp: number;
  context?: string;
}

// Question types generated by OpenAI
export type QuestionType = 
  | 'follow_up'
  | 'clarifying'
  | 'critical_thinking'
  | 'misconception_check'
  | 'expansion'
  | 'summary';

export interface GeneratedQuestion {
  id: string;
  type: QuestionType;
  question: string;
  rationale?: string;
  relatedEvent?: string;
  priority: 'low' | 'medium' | 'high';
  timestamp: number;
}

// Transcript segment from Gemini
export interface TranscriptSegment {
  id: string;
  text: string;
  timestamp: number;
  duration: number;
  isFinal: boolean;
}

// Real-time stream events
export type StreamEventType = 
  | 'init'
  | 'heartbeat'
  | 'transcript'
  | 'semantic_event'
  | 'question'
  | 'summary'
  | 'error'
  | 'status';

export interface StreamEvent<T = unknown> {
  type: StreamEventType;
  data: T;
  timestamp: number;
  sessionId: string;
}

// Session state
export interface SessionState {
  id: string;
  status: 'idle' | 'listening' | 'processing' | 'paused' | 'ended';
  startTime: number;
  endTime?: number;
  transcript: TranscriptSegment[];
  semanticEvents: SemanticEvent[];
  questions: GeneratedQuestion[];
  summary?: string;
}

// Audio chunk metadata
export interface AudioChunk {
  sessionId: string;
  chunkIndex: number;
  timestamp: number;
  duration: number;
  mimeType: string;
}

// Gemini response types
export interface GeminiTranscriptResponse {
  text: string;
  isFinal: boolean;
  confidence: number;
}

export interface GeminiSemanticResponse {
  events: Array<{
    type: SemanticEventType;
    content: string;
    confidence: number;
  }>;
}

// OpenAI question generation request
export interface QuestionGenerationRequest {
  sessionId: string;
  event: SemanticEvent;
  context: {
    recentTranscript: string;
    previousEvents: SemanticEvent[];
    previousQuestions: GeneratedQuestion[];
  };
}

// OpenAI question generation response
export interface QuestionGenerationResponse {
  questions: GeneratedQuestion[];
}

// Frontend state
export interface UIState {
  isListening: boolean;
  audioLevel: number;
  connectionStatus: 'connected' | 'connecting' | 'disconnected' | 'error';
  activeTab: 'live' | 'questions' | 'summary';
}
